title: "RJC0512NCSU CLASS BLOG"
author: "RJC0512"
description: "Blog created for NCSU ST558"

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "example@mail.com"
#twitter_username: "twitteruser"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username
BIO: Hello All,

My name is Ryan Craft.  I'm currently a middle and high school science teacher.  As many of you can imagine, this is not the most rewarding career, definitely not living up to the dream of walking into a classroom and opening young minds to the wonders of science, but rather more of yelling at students to stop trying to do tik-tok dances in the middle of class time.  So, with a background in neuroscience research and data analysis, this seems like a natural transition.  This is my story.
#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
